"""Secure key management for PoA blockchain authority signing keys.

FIX (Phase 8.5, engineering correction of a real vulnerability found during
the Phase 8 IEEE-style review): the previous implementation
(`blockchain.poa_ledger.AuthorityNode.from_label`) derived each authority's
signing "secret" deterministically from its own public label —
`sha256(f"{label}|smart-grid-poa-secret")`. Since the four labels
("Utility Operator", "Grid Supervisor", "Security Auditor",
"Data Custodian") are returned directly by `/api/blockchain/status`, and
the fixed suffix is a literal in open source code, anyone who can read
either the API response or the repository could recompute all four
"secrets" and forge a validly-signed block. This defeated the actual
security property the PoA ledger's name promises.

This module generates real Ed25519 keypairs and persists private key
material OUTSIDE source code — a git-ignored JSON file, following the
same pattern already established for `production/security/users.json` —
with an environment-variable override for containerized deployments
where secrets are injected at the platform level rather than left on disk.

Nothing here changes blockchain/poa_ledger.py's public API: it still
accepts a `Sequence[AuthorityNode]`, `AuthorityNode.from_label(label)`
still works unchanged for tests and throwaway ledgers (it now generates a
real random keypair instead of a derivable one). This module only adds a
production-grade way to obtain PERSISTENT AuthorityNode identities.
"""
from __future__ import annotations

import base64
import json
import os
import stat
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat

from blockchain.poa_ledger import AuthorityNode

DEFAULT_AUTHORITY_LABELS = [
    "Utility Operator",
    "Grid Supervisor",
    "Security Auditor",
    "Data Custodian",
]

DEFAULT_KEY_FILE = Path(__file__).resolve().parent / "authority_keys.json"

_ENV_PREFIX = "SGRID_AUTHORITY_KEY_"


def _env_var_name(label: str) -> str:
    slug = "".join(ch if ch.isalnum() else "_" for ch in label.upper())
    return f"{_ENV_PREFIX}{slug}"


def _load_key_file(key_file: Path) -> dict[str, str]:
    if key_file.exists():
        return json.loads(key_file.read_text(encoding="utf-8"))
    return {}


def _save_key_file(key_file: Path, keys: dict[str, str]) -> None:
    key_file.parent.mkdir(parents=True, exist_ok=True)
    key_file.write_text(json.dumps(keys, indent=2), encoding="utf-8")
    try:
        # Best-effort owner-only permissions. Windows ACLs aren't POSIX-mode
        # compatible, so this is a no-op there (not a security regression —
        # Windows deployments should rely on NTFS ACLs / the env-var path
        # instead; documented in docs/key_rotation_and_recovery.md).
        os.chmod(key_file, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def load_or_generate_authority_keys(
    labels: list[str] | None = None,
    key_file: Path | None = None,
) -> list[AuthorityNode]:
    """Returns AuthorityNode instances with persistent Ed25519 identities.

    Resolution order per authority, highest priority first:
      1. `SGRID_AUTHORITY_KEY_<LABEL>` environment variable — a
         base64-encoded 32-byte Ed25519 private key. Intended for
         containerized/CI deployments where secrets are injected by the
         orchestration platform (Kubernetes Secret, Docker secret, etc.)
         rather than left on the container filesystem.
      2. `key_file` (default: production/security/authority_keys.json,
         already covered by this repo's broad `data/`/`.env`-style
         gitignore conventions for local secrets — verify it is excluded
         before any commit; see docs/key_rotation_and_recovery.md).
         Generated automatically, once, on first run if missing.

    Never hardcodes a secret and never derives one from public data —
    each key is either operator-supplied (env var) or generated by
    `Ed25519PrivateKey.generate()` (a CSPRNG), then persisted.
    """
    labels = labels or DEFAULT_AUTHORITY_LABELS
    key_file = key_file or DEFAULT_KEY_FILE

    stored = _load_key_file(key_file)
    changed = False
    nodes: list[AuthorityNode] = []

    for label in labels:
        env_value = os.environ.get(_env_var_name(label))
        if env_value:
            private_bytes = base64.b64decode(env_value)
        elif label in stored:
            private_bytes = base64.b64decode(stored[label])
        else:
            private_bytes = Ed25519PrivateKey.generate().private_bytes(
                encoding=Encoding.Raw, format=PrivateFormat.Raw, encryption_algorithm=NoEncryption(),
            )
            stored[label] = base64.b64encode(private_bytes).decode("ascii")
            changed = True

        nodes.append(AuthorityNode.from_label_and_private_key(label, private_bytes))

    if changed:
        _save_key_file(key_file, stored)

    return nodes
